Error handler adjustment
PEM-Humboldt/stac-fastapi pull request #10
Opened 2024-11-27 19:58 UTC by denarch22

## 🛠️ Changes
The default error handler was adjusted and the custom exception was added

## 📝 Associated issues
[ajustar manejador de errores stac-fastApi](https://github.com/stac-utils/stac-fastapi/compare/main...PEM-Humboldt:stac-fastapi:errorHandlerAdjustment?expand=1)

2024-12-03 22:13 UTC, erikasv commented
estoy viendo los mismos cambios que en la rama `createAuth`, cambiar el objetivo del PR, hacer rebase si es necesario

2024-12-03 23:10 UTC, denarch22 commented
> estoy viendo los mismos cambios que en la rama `createAuth`, cambiar el objetivo del PR, hacer rebase si es necesario

Hola Erika,pero estuve revisando y en esta rama hice una modificación que no tiene la de createAuth que es agregar un archivo con un excepción personalidad y agregarla en el archivo de errores

2024-12-03 23:13 UTC, erikasv commented
Con mayor razón se debe cambiar la rama base del PR. No puedo revisar los cambios repetidos dos veces, solo lo que es diferente en esta rama

2024-12-03 23:46 UTC, denarch22 commented
> Con mayor razón se debe cambiar la rama base del PR. No puedo revisar los cambios repetidos dos veces, solo lo que es diferente en esta rama

ya realice el rebase

2024-12-03 23:48 UTC, erikasv commented
pero el PR tiene que apuntar a `createAuth` no a `IAvH`

2024-12-03 23:51 UTC, denarch22 commented
> pero el PR tiene que apuntar a `createAuth` no a `IAvH`

listo ya lo cambie

2024-12-04 13:10 UTC, erikasv requested changes

2024-12-04 13:10 UTC, erikasv commented on stac_fastapi/api/stac_fastapi/api/exceptions.py
En lugar de crear este archivo, agrega otro tipo de error en stac_fastapi.types.errors, y se debe manejar de la misma forma que los otros. El detalle no es necesario, este servidor no es creación no es nuestra y es más importante mantener la arquitectura y estilo original

2024-12-04 13:10 UTC, erikasv commented on stac_fastapi/api/stac_fastapi/api/errors.py
> +    app.add_exception_handler(HTTPException, http_exception_handler)
Esta excepción es demasiado genérica para lo que realmente hace, además el factory crea los errores con los códigos correspondientes, verificaste qué pasaba con solo agregar el tipo a `DEFAULT_STATUS_CODES`?

2024-12-04 13:10 UTC, erikasv commented on stac_fastapi/api/stac_fastapi/api/auth.py
> +
elimina esta linea

2024-12-04 17:50 UTC, erikasv requested changes

2024-12-04 17:50 UTC, erikasv commented on stac_fastapi/api/stac_fastapi/api/AuthMiddleware.py
> +
eliminar esta línea

2024-12-04 17:50 UTC, erikasv commented on stac_fastapi/api/stac_fastapi/api/errors.py
> +
Esta definición no debe ir aquí, debe ir con los demás errores

2024-12-04 17:50 UTC, erikasv commented on stac_fastapi/api/stac_fastapi/api/errors.py
> +        """Handle exceptions in a uniform way."""
por qué cambiar este comentario?

2024-12-04 17:50 UTC, erikasv commented on stac_fastapi/api/stac_fastapi/api/errors.py
> +        logger.error(f"Exception: {exc} - Path: {request.url} - Method: {request.method}")
por qué cambiar este log?

2024-12-04 17:50 UTC, erikasv commented on stac_fastapi/api/stac_fastapi/api/errors.py
> +    # Customize handling of request validation errors
__NO__ cambiar este comentario

2024-12-04 17:50 UTC, erikasv commented on stac_fastapi/api/stac_fastapi/api/errors.py
> +            content=ErrorResponse(code=exc.__class__.__name__, description="Invalid request format"),
deshacer estos cambios

2024-12-04 17:50 UTC, erikasv commented on stac_fastapi/api/stac_fastapi/api/errors.py
> -
restaurar la última línea en blanco. Agregar configuración al editor, no se debe borrar nunca la última línea en blanco!

2024-12-06 03:29 UTC, erikasv requested changes
A pesar de que con esta implementación se crea correctamente el manejador para UnauthorizedError en el factory, este no captura el error elevado por el middleware.

Veo estas dos posibles soluciones:
1. Cambiar el valor de status_code en el `JSONResponse` del manejador del factory (línea 677) de stac_fastapi/api/stac_fastapi/api/errors.py, así :
    ```
    status_code=DEFAULT_STATUS_CODES.get(type(exc), status_code)
    ```
    No es bueno validar solo con DEFAULT_STATUS_CODES, pero es lo menos disruptivo con el proyecto original
    > En caso de seleccionar esta opción eliminar el try-catch que encierra a `verify_token(token)` en stac_fastapi/api/stac_fastapi/api/AuthMiddleware.py

2. Dar respuesta ahí mismo en el middleware sin elevar el error, de manera similar a como se muestra en el try-catch de [esta respuesta](https://stackoverflow.com/a/76269047) (solo que no necesitamos el try-catch)

2024-12-06 03:29 UTC, erikasv commented on stac_fastapi/api/stac_fastapi/api/AuthMiddleware.py
> +from stac_fastapi.api.errors import UnauthorizedError
importar UnauthorizedError directamente desde  stac_fastapi.types

2024-12-06 03:29 UTC, erikasv commented on stac_fastapi/types/stac_fastapi/types/errors.py
> +class UnauthorizedError(Exception):
Hereda de StacApiError, no Exception

2024-12-07 13:38 UTC, erikasv requested changes

2024-12-07 13:38 UTC, erikasv commented on stac_fastapi/api/stac_fastapi/api/auth.py
> +from stac_fastapi.api.errors import UnauthorizedError
aqui también se debe importar UnauthorizedError desde stac_fastapi.types,  no desde stac_fastapi.api

2024-12-07 13:38 UTC, erikasv commented on stac_fastapi/api/stac_fastapi/api/auth.py
>      except JWTError|ExpiredSignatureError|JWTClaimsError as e:
Cambiar sintaxis de este except, falla con las versiones de python 3.10 y 3.11 (esta es la versión del dockerfile, así que se de debe garantizar funcionamiento con ella)

2024-12-07 13:53 UTC, denarch22 commented on stac_fastapi/api/stac_fastapi/api/auth.py
> +from stac_fastapi.api.errors import UnauthorizedError
ya realice el ajuste

2024-12-07 13:54 UTC, denarch22 commented on stac_fastapi/api/stac_fastapi/api/auth.py
>      except JWTError|ExpiredSignatureError|JWTClaimsError as e:
Tenia un problema como de cache en el equipo, pero ya funciono

2024-12-07 14:33 UTC, erikasv approved these changes

2024-12-07 14:53 UTC, erikasv commented
Encontré un inconveniente en la autorización, pero como esta rama ya cumplió con su cometido (retornar el código correcto) la voy a mezclar para evitar posibles problemas luego

2024-12-07 14:53 UTC, merged